version: '3'
services:
    redis:
        image: redis:7.0.5
        command: --port ${REDIS_PORT}
        ports:
          - ${REDIS_PORT}:${REDIS_PORT}
    proxy:
        build:
            context: .
            dockerfile: proxy/Dockerfile
        environment:
          - REDIS_PORT=${REDIS_PORT}
          - REDIS_HOST=${REDIS_HOST}
          - PROXY_LISTEN=${PROXY_LISTEN}
          - CACHE_EXPIRY=${CACHE_EXPIRY}
          - CACHE_CAPACITY=${CACHE_CAPACITY}
        ports:
          - ${PROXY_PORT}:${PROXY_PORT}
        volumes:
          - .:/proxy
        depends_on:
          - redis
    integration_tests:
        build:
          context: .
          dockerfile: test/Dockerfile
        environment:
          - REDIS_PORT=${REDIS_PORT}
          - REDIS_HOST=${REDIS_HOST}
          - PROXY_PORT=${PROXY_PORT}
          - CACHE_EXPIRY=${CACHE_EXPIRY}
          - CACHE_CAPACITY=${CACHE_CAPACITY}
        volumes:
          - .:/test
        depends_on:
          - proxy
          - redis