# This is the conda environment file for all dependencies
name: proxy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest=7.1.1
  - requests=2.28.1
  - mypy=0.942
  - black=22.3.0
  - pylint=2.13.4
  - isort=5.10.1